project:
  type: book
  output-dir: docs #for publishing in github pages
book:
  title: "Emergent Minds: Navigating Complexity in Psychological Systems"
  author: "Han van der Maas"
  date: "Dec 2023"
  search: true
  repo-url: https://github.com/tasospsy/complexity_book
  #repo-actions: [edit]
  downloads: [pdf]
  #downloads: [pdf, epub]
  sidebar:
    style: docked
    #background: light
  chapters:
    - index.qmd
    - ch1.qmd
    - ch2.qmd
    - ch3.qmd
    - ch4.qmd
    - ch5.qmd
    - ch6.qmd
    - ch7.qmd
    - ch8.qmd
    - references.qmd


bibliography: [referencesBBT.bib]
csl: chicago-author-date.csl

format:
  html:
    theme: cosmo
    number-depth: 4
    toc-depth: 8
    code-copy: true
    crossref:
      chapters: true
  pdf:
    documentclass: scrartcl
    #papersize: letter
    number-depth: 4
    toc-depth: 8
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
    #highlight-style: github
    #fontfamily: 
    crossref:
      chapters: true
editor: visual

