project:
  type: book
  output-dir: docs #for publishing in github pages
book:
  title: "Complex systems research in Psychology"
  author: "Han van der Maas"
  date: last-modified
  search: true
  repo-url: https://github.com/tasospsy/complexity_book
  #repo-actions: [edit]
  downloads: [pdf]
  #downloads: [pdf, epub]
  sidebar:
    style: docked
    #background: light
  chapters:
    - index.qmd
    #- call-outs-TEST.qmd
    - ch1.qmd
    - ch2.qmd
    - ch3.qmd
    - ch4n.qmd
    - ch5n.qmd
    - ch6.qmd
    - ch7.qmd
    - ch8.qmd
    - references.qmd


bibliography: [referencesBBT.bib]
csl: chicago-author-date.csl

format:
  html:
    theme: cosmo
    number-depth: 4
    toc-depth: 8
    code-copy: true
    number-sections: true
    crossref:
      chapters: true
  pdf:
    documentclass: scrreprt
    papersize: A4
    number-depth: 4
    toc-depth: 8
    number-sections: true
    keep-tex: true
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
        \usepackage[top=25mm, left=15mm, right=45mm, bottom=20mm, marginparwidth=35mm,marginparsep=5mm ]{geometry}
        \usepackage{setspace}
        \marginpar{\setstretch{1.5}\selectfont Here is your margin note text.}

    include-after-body: 
      text: |
        \printindex
    #highlight-style: github
    # geometry:
    #  - top=25mm
    #  - left=15mm
    #  - right=45mm  # Add this line to set the right margin
    #  - bottom=25mm # Add this line to set the bottom margin
    # - heightrounded
    crossref:
      chapters: true
editor: visual

