project:
  type: book
  output-dir: docs #for publishing in github pages
book:
  title: "Complex Systems Research in Psychology"
  author: "Han L. J. van der Maas"
  date: last-modified
  search: true
  #repo-actions: [edit]
  #downloads: [pdf]
  #sharing: [twitter, linkedin]
  repo-url: https://github.com/hvdmaas/complexity_book
  
  sidebar:
    logo: sfi_cover.png
    pinned: true
    tools:
          - icon: save
            menu:
              - text: Download PDF
                url:  "Complex-Systems-Research-in-Psychology.pdf"
    #style: docked
    #background: primary
    #logo: sfi_cover.png
    #tools: 
    #- icon: book
    #  href: https://www.sfipress.org/books/
    #- icon: cart
    #  href: https://a.co/d/aXyHRoK
      
  page-footer: 
    left: '<a href="https://www.sfipress.org/"><img src="csrp-online-press-logo.png" alt="Santa Fe Institute press" style="height:45px;"></a>'
    center: '© Han L. J. van der Maas, 2024'
    right: '<a href="https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1" target="_blank">CC BY-SA 4.0</a>'
    border: true
  
  chapters:
    - index.qmd
    - ch1.qmd
    - ch2.qmd
    - ch3.qmd
    - ch4n.qmd
    - ch5n.qmd
    #- ch5n_pdf.qmd
    - ch6.qmd
    - ch7.qmd
    - ch8.qmd
    - references.qmd
    
crossref:
  chapters: true
  fig-prefix: figure
  sec-prefix: section
  eq-prefix: equation

bibliography: [referencesBBT.bib]
csl: chicago-author-date.csl
#fig-cap-location: margin

monofont: 'Monaco'
monofontoptions: 
  - Scale=0.7

tbl-cap-location: bottom

format:
  html:
    output-dir: docs
    theme: cerulean
    number-depth: 4
    toc-depth: 8
    code-copy: true
    number-sections: true
    #crossref:
    #  chapters: true
    #  fig-prefix: figure
    #  sec-prefix: section
    #  eq-prefix: equation
    #cover-image: sfi_cover.png 
    favicon: sfi_cover.png 
    fontsize: '13.5pt' 
    grid:
      sidebar-width: '300px'
  docx: 
    reference-doc: my-doc-style.docx
  pdf:
    #latex-output-dir: pdf
    documentclass: scrreprt
    papersize: A4
    number-depth: 4
    toc-depth: 8
    number-sections: true
    keep-tex: true
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
        \usepackage[top=25mm, left=15mm, right=65mm, bottom=25mm, marginparwidth=55mm, marginparsep=5mm]{geometry}
        \usepackage{setspace} % For setting the line spacing
        \usepackage{marginnote} % For improved margin notes
        % Redefine the marginnote command to include setstretch
        \let\oldmarginnote\marginnote
        \renewcommand{\marginnote}[1]{%
        \oldmarginnote{\setstretch{0.8}\selectfont#1}%
        }
    include-after-body: 
      text: |
        \printindex
    highlight-style: github
    code-block-bg: "#F0F0F0"
    # geometry:
    #  - top=25mm
    #  - left=15mm
    #  - right=45mm  # Add this line to set the right margin
    #  - bottom=25mm # Add this line to set the bottom margin
    # - heightrounded
    #crossref:
    #  chapters: true
    #  fig-prefix: figure
    #  sec-prefix: section
    #  eq-prefix: equation
  
editor: visual
